---
- name: Converge
  hosts: all

  # Ensure Ansible become root when running on localhost
  become: true
  become_method: community.general.sudosu

  # Gathering facts requires a container with Python installed
  gather_facts: true

  vars:
    # Test the monitoring mode
    onionprobe_operation: standalone

    # Install via repository
    onionprobe_installation: repository

    # Configure Podman as the container runtime
    # This is still experimental as of 2024-10
    #onionprobe_container_runtime: podman

  pre_tasks:
    # Install the ACL package
    # https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary#56379678
    - name: Install acl
      ansible.builtin.package:
        name: acl

    # Sudo is needed by some Ansible modules, and may not be available in the
    # container instance
    - name: Install sudo
      ansible.builtin.package:
        name: sudo

    #- name: Create the admin group
    #  ansible.builtin.group:
    #    name: "admin"

    # Users in admin group should have passwordless sudo
    # This ensures scripts that need sudo can run
    #- name: Configure passwordless sudo for the admin group
    #  ansible.builtin.lineinfile:
    #    create : true
    #    owner  : "root"
    #    group  : "root"
    #    mode   : "0600"
    #    line   : "%admin ALL=(ALL) NOPASSWD : ALL"
    #    path   : /etc/sudoers.d/90-admin

  roles:
    - onionprobe
