---
#
# Onionprobe installation using pip
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
#

- name: Installs Onionprobe using pip
  block:
  - name: Install ansible.builtin.pip dependencies on Debian-like systems
    when: ansible_os_family == 'Debian'
    ansible.builtin.apt:
      name:
        - python3-pip
        - python3-virtualenv
      state: present

  - name: Install onionprobe package
    ansible.builtin.pip:
      name: onionprobe
      extra_args: '--upgrade'
      virtualenv: "{{ onionprobe_virtualenv }}"
