#
# Onionprobe role
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Validation
#

- name: Onionprobe config validation
  include_tasks: validation/main.yml

#
# Installation
#

- name: Onionprobe installation using distro-supplied package
  when: onionprobe_installation == 'package'
  include_tasks: installation/distro.yml

- name: Onionprobe installation using pip
  when: onionprobe_installation == 'pip'
  include_tasks: installation/pip.yml

- name: Onionprobe installation using a repository working copy
  when: onionprobe_installation == 'repository'
  include_tasks: installation/repository.yml

#
# Operation
#

- name: Onionprobe single service
  when: onionprobe_operation == 'single'
  include_tasks: operation/single.yml

- name: Onionprobe full standalone monitor node
  when: onionprobe_operation == 'standalone'
  include_tasks: operation/standalone.yml
