---
#
# Onionprobe user and group handling
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: environment | user | Manage group and user
  block:
    - name: environment | user | Manage the onionprobe group
      ansible.builtin.group:
        name : "{{ onionprobe_group }}"
        gid  : "{{ onionprobe_gid }}"

    - name: environment | user | Manage the onionprobe user
      ansible.builtin.user:
        name          : "{{ onionprobe_user }}"
        append        : true
        uid           : "{{ onionprobe_uid }}"
        group         : "{{ onionprobe_group }}"
        groups        : "{{ ['docker'] if (onionprobe_container_runtime == 'docker' and onionprobe_operation == 'standalone') else [] }}"
        create_home   : false
        home          : "{{ onionprobe_home }}"
        password_lock : true

    - name: environment | user | Manage the Onionprobe user folder
      when: onionprobe_home != onionprobe_path
      ansible.builtin.file:
        path  : "{{ onionprobe_home }}"
        owner : "{{ onionprobe_user }}"
        group : "{{ onionprobe_group }}"
        state : directory
        mode    : '0750'
        recurse : false
