---
#
# Alertmanager configuration file
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
#

- name: Configure alertmanager
  block:
    - name: Create the alertmanager contrib config folder
      ansible.builtin.file:
        path    : "{{ onionprobe_path }}/contrib/configs/alertmanager"
        owner   : "{{ onionprobe_user }}"
        group   : "{{ onionprobe_user }}"
        mode    : '0755'
        state   : directory
        recurse : false

    - name: Setup the altertmanager contrib config
      # Ownership here depends on the UID and GID used by the Alertmanager container service
      ansible.builtin.template:
        src   : "{{ onionprobe_alertmanager_template }}"
        dest  : "{{ onionprobe_path }}/contrib/configs/alertmanager/alertmanager.yml"
        owner : "nobody"
        group : "nogroup"
        mode  : '0640'
        force : yes
