---
#
# Container configuration
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
#

- name: configuration | containers | Setup the container environment file
  ansible.builtin.template:
    src   : containers/env.j2
    dest  : "{{ onionprobe_path }}/.env"
    owner : "{{ onionprobe_user }}"
    group : "{{ onionprobe_group }}"
    mode  : '0640'
    force : true

- name: configuration | containers | Create the podman config folder for the monitor user
  when: onionprobe_container_runtime == 'podman'
  ansible.builtin.file:
    path  : "{{ onionprobe_path }}/.config/containers/containers.conf.d"
    owner : "{{ onionprobe_user }}"
    group : "{{ onionprobe_group }}"
    state : directory
    mode  : '0755'

- name: configuration | containers | Configure podman's containers.conf for the monitor user
  when: onionprobe_container_runtime == 'podman'
  ansible.builtin.copy:
    remote_src : true
    src        : "{{ onionprobe_path }}/configs/podman/containers.conf"
    dest       : "{{ onionprobe_path }}/.config/containers/containers.conf.d"
    owner      : root
    group      : root
    mode       : '0644'
