---
#
# Onionprobe Ansible role test playbook
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
#

- name: Standalone, full monitor operation mode
  hosts: standalone

  # Gathering facts requires a container with Python installed
  gather_facts: true

  vars:
    # Test the monitoring mode
    onionprobe_operation: monitor

    # Install via repository
    onionprobe_installation: repository

    # Configure Podman as the container runtime
    onionprobe_container_runtime: podman

    # Do not enable the service, since the image is not started with systemd as PID 1
    onionprobe_enable_service: false

  pre_tasks:
    - name: Run pre-tasks
      ansible.builtin.include_tasks: tasks.yml

  roles:
    - onionprobe

- name: Single operation mode installing Onionprobe via distro package
  hosts: single-distro

  # Gathering facts requires a container with Python installed
  gather_facts: true

  vars:
    # Test the single mode
    onionprobe_operation: single

    # Install via distro
    onionprobe_installation: distro

    # Do not enable the service, since the image is not started with systemd as PID 1
    onionprobe_enable_service: false

  pre_tasks:
    - name: Run pre-tasks
      ansible.builtin.include_tasks: tasks.yml

  roles:
    - onionprobe

- name: Single operation mode installing Onionprobe via pip
  hosts: single-pip

  # Gathering facts requires a container with Python installed
  gather_facts: true

  vars:
    # Test the single mode
    onionprobe_operation: single

    # Install via distro
    onionprobe_installation: pip

    # Do not enable the service, since the image is not started with systemd as PID 1
    onionprobe_enable_service: false

  pre_tasks:
    - name: Run pre-tasks
      ansible.builtin.include_tasks: tasks.yml

  roles:
    - onionprobe

- name: Single operation mode installing Onionprobe via repository
  hosts: single-repository

  # Gathering facts requires a container with Python installed
  gather_facts: true

  vars:
    # Test the single mode
    onionprobe_operation: single

    # Install via distro
    onionprobe_installation: repository

    # Do not enable the service, since the image is not started with systemd as PID 1
    onionprobe_enable_service: false

  pre_tasks:
    - name: Run pre-tasks
      ansible.builtin.include_tasks: tasks.yml

  roles:
    - onionprobe
