---
#
# Onionprobe Ansible molecule test
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

dependency:
  name: galaxy
  options:
    requirements-file: requirements-podman.yml

driver:
  name: podman
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

platforms:
  - name: standalone
    # Use a container with Python pre-installed
    image           : docker.io/python:bookworm
    pre_build_image : true
    privileged      : true

    # Container entrypoint
    # A command that keeps the container running
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}

    # The Python Debian container images ships with multiple Python
    # executables.
    #
    # In order to use Python from the Debian package, PATH must be set without
    # prioritizing /usr/local/bin.
    #
    # This may avoid unreliability issues such as
    # https://gitlab.torproject.org/tpo/onion-services/ansible/onionprobe-role/-/merge_requests/5
    #
    # For details, check https://hub.docker.com/_/python
    env:
      PATH: /sbin:/usr/sbin:/bin:/usr/bin

  - name: single-distro
    # Use a container with Python pre-installed
    image           : docker.io/python:bookworm
    pre_build_image : true
    privileged      : true

    # Container entrypoint
    # A command that keeps the container running
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}

    # The Python Debian container images ships with multiple Python
    # executables.
    #
    # In order to use Python from the Debian package, PATH must be set without
    # prioritizing /usr/local/bin.
    #
    # This may avoid unreliability issues such as
    # https://gitlab.torproject.org/tpo/onion-services/ansible/onionprobe-role/-/merge_requests/5
    #
    # For details, check https://hub.docker.com/_/python
    env:
      PATH: /sbin:/usr/sbin:/bin:/usr/bin

  - name: single-pip
    # Use a container with Python pre-installed
    image           : docker.io/python:bookworm
    pre_build_image : true
    privileged      : true

    # Container entrypoint
    # A command that keeps the container running
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}

    # The Python Debian container images ships with multiple Python
    # executables.
    #
    # In order to use Python from the Debian package, PATH must be set without
    # prioritizing /usr/local/bin.
    #
    # This may avoid unreliability issues such as
    # https://gitlab.torproject.org/tpo/onion-services/ansible/onionprobe-role/-/merge_requests/5
    #
    # For details, check https://hub.docker.com/_/python
    env:
      PATH: /sbin:/usr/sbin:/bin:/usr/bin

  - name: single-repository
    # Use a container with Python pre-installed
    image           : docker.io/python:bookworm
    pre_build_image : true
    privileged      : true

    # Container entrypoint
    # A command that keeps the container running
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}

    # The Python Debian container images ships with multiple Python
    # executables.
    #
    # In order to use Python from the Debian package, PATH must be set without
    # prioritizing /usr/local/bin.
    #
    # This may avoid unreliability issues such as
    # https://gitlab.torproject.org/tpo/onion-services/ansible/onionprobe-role/-/merge_requests/5
    #
    # For details, check https://hub.docker.com/_/python
    env:
      PATH: /sbin:/usr/sbin:/bin:/usr/bin

# The Python Debian container images ships with multiple Python
# executables.
#
# In order to use Python from the Debian package, PATH must be set without
# prioritizing /usr/local/bin.
#
# This may avoid unreliability issues such as
# https://gitlab.torproject.org/tpo/onion-services/ansible/onionprobe-role/-/merge_requests/5
#
# For details, check https://hub.docker.com/_/python
#
# This is commented out since setting PATH directly in the container
# environment is more reliable.
#provisioner:
#  name: ansible
#  env:
#    PATH: /sbin:/usr/sbin:/bin:/usr/bin
