---
#
# Onionprobe standalone monitoring mode
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
#

- name: Onionprobe configuration
  include_tasks: ../resources/configuration/onionprobe.yml
  vars:
    owner: "{{ onionprobe_user }}"
    group: "{{ onionprobe_group }}"

- name: Alertmanager configuration
  include_tasks: ../resources/configuration/alertmanager.yml

- name: Container configuration
  include_tasks: ../resources/configuration/container.yml

- name: Service configuration
  include_tasks: ../resources/service/systemd/unit.yml
